name: CI

on:
  pull_request:
    paths-ignore:
      - "**.md"
    branches: [main]
  push:
    paths-ignore:
      - "**.md"
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: [macos-latest]

    steps:
      - name: Test plugin
        uses: asdf-vm/actions/plugin-test@v1
        with:
          command: "openshift-install version"
