name: CI

on:
  pull_request:
    paths-ignore:
      - "**.md"
    branches: [main]
  push:
    paths-ignore:
      - "**.md"
    branches: [main]

jobs:
  plugin_test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest

    steps:
      - name: Test plugin
        uses: asdf-vm/actions/plugin-test@v1
        with:
          command: "openshift-install version"
